<?php

namespace AppBundle\Repository;

/**
 * ZacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZacRepository extends \Doctrine\ORM\EntityRepository
{
}
