<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHu4nu3f\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHu4nu3f/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHu4nu3f.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHu4nu3f\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHu4nu3f\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hu4nu3f',
    'container.build_id' => 'c5b6659c',
    'container.build_time' => 1524214456,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHu4nu3f');
